---
title: "Reproducible Research: Peer Assessment 1"
output: The html file
Author: Khalil Naseraldin
Date : 20-12-2018
  html_document:
    keep_md: true
    
---

## Step1 - Code for reading in the dataset and/or processing the data
#Assuming the data is in the current project

library(ggplot2)
library(dplyr)
activity <- read.csv("./activity.csv", header = TRUE)
# convert date to convenient format
activity$date <- as.POSIXct(activity$date, "%Y-%m-%d")
weekday <- weekdays(activity$date)
activity <- cbind(activity,weekday)
summary(activity)
head(activity)

## Step2 - Histogram of the total number of steps taken each day
summed_steps<- aggregate(steps ~ date, activity, FUN=sum)

head(summed_steps)
#Use the base plotting to show a histogram
hist(summed_steps$steps, 
     col="red", 
     xlab = "Frequency", 
     ylab = "Steps",
     main = "Total Number Of Steps Taken Each day")

## Step3 - Mean and median number of steps taken each day
#Calculation
Mean <- mean(summed_steps$steps)
Median <- median(summed_steps$steps)
#Print results of mean and median
Mean
Median

## Step4 - Time series plot of the average number of steps taken: What is the average daily activity pattern?

# Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across #all days (y-axis)
#aggregation of steps over time interval (of 5 min)
agginterval <- aggregate(steps ~ interval, activity, FUN=sum)
#Plotting line graph using plot() from Base Plotting for Total Steps vs 5-Minute Interval
plot(agginterval$interval, agginterval$steps, 
     type = "l", lwd = 2,
     xlab = "Interval", 
     ylab = "Total Steps",
     main = "Total Steps vs. 5-Minute Interval")

# Step5 - Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
filter(agginterval, steps==max(steps))

## Imputing missing values 
## Step6 - Code to describe and show a strategy for imputing missing data
# 1.Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)
table(is.na(activity))

# 2.Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For     example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.

mean_interval<- aggregate(steps ~ interval, activity, FUN=mean)
newMerged <- merge(x=activity, y=mean_interval, by="interval")

#Replace the NA values with the mean for that 5-minute interval
newMerged$steps <- ifelse(is.na(newMerged$steps.x), newMerged$steps.y, newMerged$steps.x)

#Here is the merged dataset which will be subsetted in the next step by removing not required columns
head(newMerged)

# 3. Create a new dataset that is equal to the original dataset but with the missing data filled in.
newMerged <- select(newMerged, steps, date, interval)
head(newMerged)

## Step7 - Histogram of the total number of steps taken each day after missing values are imputed
# Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?

#Aggregating(summation) of steps over date
aggsteps_new<- aggregate(steps ~ date, newMerged, FUN=sum)

#Plotting : Setting up the pannel for one row and two columns
par(mfrow=c(1,2))

#Histogram after imputing NA values with mean of 5-min interval
hist(aggsteps_new$steps, 
     col="green",
     xlab = "Steps", 
     ylab = "Frequency",
     ylim = c(0,35),
     main = "Total Number Of Steps Taken Each day \n(After imputing NA values with \n mean of 5-min interval)",
     cex.main = 0.7)

#Histogram with the orginal dataset
hist(aggsteps$steps, 
     col="red", 
     xlab = "Steps", 
     ylab = "Frequency",
     ylim = c(0,35),
     main = "Total Number Of Steps Taken Each day \n(Orginal Dataset)",
     cex.main = 0.7)

par(mfrow=c(1,1)) #Resetting the panel
Mean_new <- mean(aggsteps_new$steps)
Median_new <- median(aggsteps_new$steps)

#Comparing Means
paste("New Mean      :", round(Mean_new,2), "," ,  
      " Original Mean :", round(Mean,2),"," , 
      " Difference :",round(Mean_new,2) -  round(Mean,2))

#Comparing Medians
paste("New Median    :", Median_new, ",", 
      " Original Median :", Median,"," , 
      " Difference :",round(Median_new-Median,2))      

## Step 8 -Are there differences in activity patterns between weekdays and weekends?
#install.packages("chron")
library(chron)

# Create a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.
table(is.weekend(newMerged$date))
newMerged$dayofweek <- ifelse(is.weekend(newMerged$date), "weekend", "weekday")
table(newMerged$dayofweek)
head(newMerged)

# Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). The plot should look something like the following, which was created using simulated data:
meaninterval_new<- aggregate(steps ~ interval + dayofweek, newMerged, FUN=mean)
head(meaninterval_new)
ggplot(meaninterval_new, aes(x=interval, y=steps)) + 
  geom_line(color="blue", size=1) + 
  facet_wrap(~dayofweek, nrow=2) +
  labs(x="\nInterval", y="\nNumber of steps")

  
